apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brewz
  namespace: stable-tarpon
spec:
  project: default
  source:
    path: manifests/brewz
    repoURL: https://github.com/dudesweet/techxchange-gitops-lab.git
    targetRevision: HEAD
  destination:
    namespace: stable-tarpon
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
